# Generated by Django 5.2.10 on 2026-01-18 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField()),
                ('defender_card', models.IntegerField()),
                ('win_rule', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('RESPONDED', 'RESPONDED'), ('FINISHED', 'FINISHED')], default='REQUESTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker_games', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
