# Generated by Django 5.2.10 on 2026-01-19 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.IntegerField()),
                ('defender_card', models.IntegerField(blank=True, null=True)),
                ('win_rule', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', '진행중'), ('RESPONDED', 'CounterAttack'), ('FINISHED', '종료')], default='REQUESTED', max_length=15)),
                ('attacker_result', models.CharField(choices=[('win', '승리'), ('lose', '패배'), ('draw', '무승부'), ('pending', '대기중')], default='pending', max_length=10)),
                ('defender_result', models.CharField(choices=[('win', '승리'), ('lose', '패배'), ('draw', '무승부'), ('pending', '대기중')], default='pending', max_length=10)),
                ('attacker_score_change', models.IntegerField(default=0)),
                ('defender_score_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker_games', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
