# Generated by Django 5.2.10 on 2026-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_defender_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('REQUESTED', '진행중'), ('RESPONDED', 'CounterAttack'), ('FINISHED', '종료')], default='REQUESTED', max_length=15),
        ),
    ]
